name: "Actions for pull request synchronize"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-pr-status:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
        IS_DRAFT: ${{ steps.check-pr-status.outputs.IS_DRAFT }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - id:   check-pr-status
        name: Check pr status
        run: |
          gh pr checkout ${{ github.event.number }}
          echo "IS_DRAFT=`gh pr status --json isDraft | jq -r '.currentBranch.isDraft'`" >> $GITHUB_OUTPUT

  execute:
    needs:   check-pr-status
    if:      needs.check-pr-status.outputs.IS_DRAFT == true
    runs-on: ubuntu-latest

    steps:
      - name: Check
        run:  echo ${{ needs.check-pr-status.outputs.IS_DRAFT }}

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set version
        run:  echo "PACKAGE_VERSION=`node -pe "require('./package.json')['version']"`" >> $GITHUB_ENV

      - name: Echo version
        env:
          PACKAGE_VERSION:  ${{ env.PACKAGE_VERSION }}
        run: |
          echo $PACKAGE_VERSION
