name: "Actions for pull request synchronize"

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  execute:
    runs-on: ubuntu-latest

    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check pr status
        run:  |
          gh pr checkout ${{ github.event.number }}
          gh pr status --json isDraft | jq -r '.currentBranch.isDraft'

      - name: Set version
        run:  echo "PACKAGE_VERSION=`node -pe "require('./package.json')['version']"`" >> $GITHUB_ENV

      - name: Echo version
        env:
          PACKAGE_VERSION:  ${{ env.PACKAGE_VERSION }}
        run: |
          echo $PACKAGE_VERSION
